const ONE_MINUTE = 60 * 1000
const ONE_HOUR = 60 * ONE_MINUTE
const ONE_DAY = 24 * ONE_HOUR
const ONE_WEEK = 7 * ONE_DAY

const CRAWL_INTERVAL = ONE_HOUR * 10
const REMOVE_DEAD_NODE = CRAWL_INTERVAL * 2 + 60 * 1000

module.exports = {
	throttle: {
		concurrency: 20,
		perTimeSpan: 10,
		timeSpanMs: 1000
	},
	MIN_CONTACT_INTERVAL: ONE_MINUTE,
	CRAWL_INTERVAL,
	REMOVE_DEAD_NODE,
	CONTINUOUS_FAILURE_BEFORE_REMOVAL: 10,
	NODE_CAPACITY: 100,
	RECHECK_UNREACHABLE_INTERVAL: ONE_WEEK,
}